# Imports

In [125]:
%%capture
import pandas as pd 
import re
from pathlib import Path
# from datasets import load_dataset
from importlib import reload
# from utils.eval import send_openrouter_request, models
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

if torch.cuda.is_available():
    device = "cuda"

torch.cuda.is_available()

# Data generation
Creating transcript excerpts.

In [124]:
# load transcripts
dir = Path('../data/transcripts')
doc_paths = sorted(dir.glob('*.txt'))

In [123]:
from pathlib import Path

def parse_transcript(doc_path, speakers):
    """
    Parse transcript into line-level records.

    A turn is defined as all contiguous lines spoken by the same speaker.
    If a line starts with 'SPEAKER:', that starts a new turn.
    Otherwise, the line is treated as a continuation of the current turn.

    Returns
    -------
    lines : list[dict]
        Each dict has:
        - line_id
        - turn_id
        - turn_speaker
        - line_text
    """
    with Path(doc_path).open("r", encoding = "utf-8") as f:
        raw_lines = [line.strip() for line in f if line.strip()]

    lines = []
    current_speaker = None
    current_turn_id = 0
    line_id = 0

    for raw_line in raw_lines:
        matched_speaker = None
        text = raw_line

        for speaker in speakers:
            prefix = f"{speaker}:"
            if raw_line.startswith(prefix):
                matched_speaker = speaker
                text = raw_line[len(prefix):].strip()
                break

        if matched_speaker is not None:
            current_speaker = matched_speaker
            current_turn_id += 1

        if current_speaker is not None:
            line_id += 1
            lines.append({
                "line_id": line_id,
                "turn_id": current_turn_id,
                "turn_speaker": current_speaker,
                "line_text": text,
            })

    return lines

In [ ]:
# so we have some unlabeled text - and we want the model to try splitting it out into lines 
# (it'll just say "Person A and Person B" - and then we have to map the breakdowns roughly; this gives us another point of comparison)
# it is tough since the LLM won't have names...

In [4]:
lines = parse_transcript(
    doc_paths[2],
    speakers = ["JO LING KENT", "DARIO AMODEI"]
)

In [ ]:
import math
from collections import Counter

excerpts = []
window_size = 20

for n in range(len(lines) - 20 + 1):
    segment = lines[n: n + window_size]
    
    current_speaker = ''
    baseline_text = ''
    turns = []
    for l in segment:
        if current_speaker != l['turn_speaker']:
            current_speaker = l['turn_speaker']
            baseline_text += l['turn_speaker']+ ': ' + l['line_text'] + '\n'
        else:
            baseline_text += l['line_text'] + '\n'
    
    min_turn = segment[0]['turn_id']
    max_turn = segment[-1]['turn_id']


    e_dict = {
        'source': f'{n}:{n+window_size}',
        'lines': segment,
        'speakers': set([l['turn_speaker'] for l in segment]),
        'speaker_line_count': dict(Counter(l['turn_speaker'] for l in segment)),
        'baseline_text': baseline_text,
        'unlabeled_text': ''.join([f'{l['line_text']}\n' for l in segment]),
        #'corrupted_labels': a case where the labels are mis-attributed and the model needs to "repair" it
        'num_turns': max_turn - min_turn
        }

    excerpts.append(e_dict)

excerpts

[{'source': '0:20',
  'lines': [{'line_id': 1,
    'turn_id': 1,
    'turn_speaker': 'JO LING KENT',
    'line_text': 'All right. Thank you for doing this with us today.'},
   {'line_id': 2,
    'turn_id': 2,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': 'Thank-- thanks for having me.'},
   {'line_id': 3,
    'turn_id': 3,
    'turn_speaker': 'JO LING KENT',
    'line_text': 'We appreciate you taking the time. You are Dario Amodei, the CEO of Anthropic. Is that right?'},
   {'line_id': 4,
    'turn_id': 4,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': "That's correct, yes."},
   {'line_id': 5,
    'turn_id': 5,
    'turn_speaker': 'JO LING KENT',
    'line_text': "Great. Well, I-- my first question to you is why won't you release Anthropic's AI without restrictions to the U.S. government?"},
   {'line_id': 6,
    'turn_id': 6,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': 'Yeah. So, you know, we should maybe back up a bit for a little bit of context. So, you know, Anthropic actually has been the most lean forward of all the AI companies in working with the U.S. government and working with the U.S. military. We were the first company to, you know, put our models on the classified cloud.'},
   {'line_id': 7,
    'turn_id': 6,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': "We were the first company to make custom models for national security purposes. We're deployed across the intelligence community and military for applications like cyber, you know, combat support operations, various things like this. And, you know, the reason we've done this is, you know, I-- I believe that we have to defend our country."},
   {'line_id': 8,
    'turn_id': 6,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': "I believe we have to defend our country from autocratic adversaries like China and like Russia. And so we've been-- we've been very, you know, we've been very lean forward. We have a substantial, you know, public sec team-- public sector team."},
   {'line_id': 9,
    'turn_id': 6,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': "But, you know, I have always believed that, you know, as we defend ourselves against our autocratic adversaries, we have to do so in ways that defend our democratic values and preserve our democratic values. And so we have said to the Department of War that we are okay with all use cases, basically 98% or 99% of the use cases they want to do, except for two that we're concerned about."},
   {'line_id': 10,
    'turn_id': 6,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': "One is domestic mass surveillance. There, we're worried that, you know, things may become possible with AI that weren't possible before. An example of this is something like taking data collected by private firms, having it bought by the government, and analyzing it in mass by AI."},
   {'line_id': 11,
    'turn_id': 6,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': "That actually isn't illegal. It was just never useful before the era of AI, so there's this way in which domestic mass surveillance is getting ahead of the law. The technology's advancing so fast that it's out of step with the law."},
   {'line_id': 12,
    'turn_id': 6,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': "That's case number one. Case number two is fully autonomous weapons. This is not the partially autonomous weapons that are used in Ukraine or, you know, could potentially be used in Taiwan today. This is the idea of making weapons that fire without any human involvement."},
   {'line_id': 13,
    'turn_id': 6,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': 'Now, even those, I think that, you know, they, you know, our adversaries may at some point have them so perhaps, you know, they may-- they may at some point be needed for the defense of democracy. But we have some concerns about them. First, the AI systems of today are nowhere near reliable enough to make fully autonomous weapons.'},
   {'line_id': 14,
    'turn_id': 6,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': "You know, anyone who's worked with AI models understands that there's a basic unpredictability to them that in a purely technical way we have not solved. And there's an oversight question too. If you have a large army of drones or robots that can operate without any human oversight, where there aren't human soldiers to make the decisions about who to target, who to shoot at, that-- that presents concerns. And we need to have a conversation about-- about how that's overseen. And we haven't had that conversation yet. And so we feel strongly that, you know, for-- for, you know, those two use cases should-- should not be allowed."},
   {'line_id': 15,
    'turn_id': 7,
    'turn_speaker': 'JO LING KENT',
    'line_text': "The Pentagon has told us that they have agreed in principle to these two restrictions, and they wanted to strike a deal. Why couldn't an agreement be reached?"},
   {'line_id': 16,
    'turn_id': 8,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': 'So there were, you know, there there were kind of several stages of this, all done quickly and kind of all, you know, determined by the kind of three-day, you know, the kind of very limited three-day window that they gave us, right.'},
   {'line_id': 17,
    'turn_id': 8,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': "They gave us an ultimatum to, you know, to agree to their terms in three days or, you know, be designated a supply chain risk or Defense Production Act, I guess we'll get to that later. But during that time, there were-- there were a few back and forths."},
   {'line_id': 18,
    'turn_id': 8,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': 'You know, at one point, they sent us language that, you know, appeared on the surface to meet our terms, but it had all kinds of language like, "If the Pentagon deems it appropriate," or, you know, or, you know, or to do anything-- "to do anything in line with laws."'},
   {'line_id': 19,
    'turn_id': 8,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': "So it didn't actually concede in any-- in-- it didn't actually concede in any meaningful way. And-- and there were further steps of it that-- that also did not concede in any meaningful way. We have wanted to strike a deal since the beginning."},
   {'line_id': 20,
    'turn_id': 8,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': 'If you want to get a sense of the Pentagon\'s position of it, the Pentagon spokesman, Sean Parnell the day before tweet, you know, he reiterated their position, "We only allow all lawful use." And this was the same as when they sent-- what they sent us-- they sent us their terms. So they-- they have not exceeded in and in-- in-- in-- in-- in-- in-- they have not in any way-- agree-- agreed to our exceptions in any meaningful way.'}],
  'speakers': {'DARIO AMODEI', 'JO LING KENT'},
  'speaker_line_count': {'JO LING KENT': 4, 'DARIO AMODEI': 16},
  'baseline_text': 'JO LING KENT: All right. Thank you for doing this with us today.\nDARIO AMODEI: Thank-- thanks for having me.\nJO LING KENT: We appreciate you taking the time. You are Dario Amodei, the CEO of Anthropic. Is that right?\nDARIO AMODEI: That\'s correct, yes.\nJO LING KENT: Great. Well, I-- my first question to you is why won\'t you release Anthropic\'s AI without restrictions to the U.S. government?\nDARIO AMODEI: Yeah. So, you know, we should maybe back up a bit for a little bit of context. So, you know, Anthropic actually has been the most lean forward of all the AI companies in working with the U.S. government and working with the U.S. military. We were the first company to, you know, put our models on the classified cloud.\nWe were the first company to make custom models for national security purposes. We\'re deployed across the intelligence community and military for applications like cyber, you know, combat support operations, various things like this. And, you know, the reason we\'ve done this is, you know, I-- I believe that we have to defend our country.\nI believe we have to defend our country from autocratic adversaries like China and like Russia. And so we\'ve been-- we\'ve been very, you know, we\'ve been very lean forward. We have a substantial, you know, public sec team-- public sector team.\nBut, you know, I have always believed that, you know, as we defend ourselves against our autocratic adversaries, we have to do so in ways that defend our democratic values and preserve our democratic values. And so we have said to the Department of War that we are okay with all use cases, basically 98% or 99% of the use cases they want to do, except for two that we\'re concerned about.\nOne is domestic mass surveillance. There, we\'re worried that, you know, things may become possible with AI that weren\'t possible before. An example of this is something like taking data collected by private firms, having it bought by the government, and analyzing it in mass by AI.\nThat actually isn\'t illegal. It was just never useful before the era of AI, so there\'s this way in which domestic mass surveillance is getting ahead of the law. The technology\'s advancing so fast that it\'s out of step with the law.\nThat\'s case number one. Case number two is fully autonomous weapons. This is not the partially autonomous weapons that are used in Ukraine or, you know, could potentially be used in Taiwan today. This is the idea of making weapons that fire without any human involvement.\nNow, even those, I think that, you know, they, you know, our adversaries may at some point have them so perhaps, you know, they may-- they may at some point be needed for the defense of democracy. But we have some concerns about them. First, the AI systems of today are nowhere near reliable enough to make fully autonomous weapons.\nYou know, anyone who\'s worked with AI models understands that there\'s a basic unpredictability to them that in a purely technical way we have not solved. And there\'s an oversight question too. If you have a large army of drones or robots that can operate without any human oversight, where there aren\'t human soldiers to make the decisions about who to target, who to shoot at, that-- that presents concerns. And we need to have a conversation about-- about how that\'s overseen. And we haven\'t had that conversation yet. And so we feel strongly that, you know, for-- for, you know, those two use cases should-- should not be allowed.\nJO LING KENT: The Pentagon has told us that they have agreed in principle to these two restrictions, and they wanted to strike a deal. Why couldn\'t an agreement be reached?\nDARIO AMODEI: So there were, you know, there there were kind of several stages of this, all done quickly and kind of all, you know, determined by the kind of three-day, you know, the kind of very limited three-day window that they gave us, right.\nThey gave us an ultimatum to, you know, to agree to their terms in three days or, you know, be designated a supply chain risk or Defense Production Act, I guess we\'ll get to that later. But during that time, there were-- there were a few back and forths.\nYou know, at one point, they sent us language that, you know, appeared on the surface to meet our terms, but it had all kinds of language like, "If the Pentagon deems it appropriate," or, you know, or, you know, or to do anything-- "to do anything in line with laws."\nSo it didn\'t actually concede in any-- in-- it didn\'t actually concede in any meaningful way. And-- and there were further steps of it that-- that also did not concede in any meaningful way. We have wanted to strike a deal since the beginning.\nIf you want to get a sense of the Pentagon\'s position of it, the Pentagon spokesman, Sean Parnell the day before tweet, you know, he reiterated their position, "We only allow all lawful use." And this was the same as when they sent-- what they sent us-- they sent us their terms. So they-- they have not exceeded in and in-- in-- in-- in-- in-- in-- they have not in any way-- agree-- agreed to our exceptions in any meaningful way.\n',
  'unlabeled_text': 'All right. Thank you for doing this with us today.\nThank-- thanks for having me.\nWe appreciate you taking the time. You are Dario Amodei, the CEO of Anthropic. Is that right?\nThat\'s correct, yes.\nGreat. Well, I-- my first question to you is why won\'t you release Anthropic\'s AI without restrictions to the U.S. government?\nYeah. So, you know, we should maybe back up a bit for a little bit of context. So, you know, Anthropic actually has been the most lean forward of all the AI companies in working with the U.S. government and working with the U.S. military. We were the first company to, you know, put our models on the classified cloud.\nWe were the first company to make custom models for national security purposes. We\'re deployed across the intelligence community and military for applications like cyber, you know, combat support operations, various things like this. And, you know, the reason we\'ve done this is, you know, I-- I believe that we have to defend our country.\nI believe we have to defend our country from autocratic adversaries like China and like Russia. And so we\'ve been-- we\'ve been very, you know, we\'ve been very lean forward. We have a substantial, you know, public sec team-- public sector team.\nBut, you know, I have always believed that, you know, as we defend ourselves against our autocratic adversaries, we have to do so in ways that defend our democratic values and preserve our democratic values. And so we have said to the Department of War that we are okay with all use cases, basically 98% or 99% of the use cases they want to do, except for two that we\'re concerned about.\nOne is domestic mass surveillance. There, we\'re worried that, you know, things may become possible with AI that weren\'t possible before. An example of this is something like taking data collected by private firms, having it bought by the government, and analyzing it in mass by AI.\nThat actually isn\'t illegal. It was just never useful before the era of AI, so there\'s this way in which domestic mass surveillance is getting ahead of the law. The technology\'s advancing so fast that it\'s out of step with the law.\nThat\'s case number one. Case number two is fully autonomous weapons. This is not the partially autonomous weapons that are used in Ukraine or, you know, could potentially be used in Taiwan today. This is the idea of making weapons that fire without any human involvement.\nNow, even those, I think that, you know, they, you know, our adversaries may at some point have them so perhaps, you know, they may-- they may at some point be needed for the defense of democracy. But we have some concerns about them. First, the AI systems of today are nowhere near reliable enough to make fully autonomous weapons.\nYou know, anyone who\'s worked with AI models understands that there\'s a basic unpredictability to them that in a purely technical way we have not solved. And there\'s an oversight question too. If you have a large army of drones or robots that can operate without any human oversight, where there aren\'t human soldiers to make the decisions about who to target, who to shoot at, that-- that presents concerns. And we need to have a conversation about-- about how that\'s overseen. And we haven\'t had that conversation yet. And so we feel strongly that, you know, for-- for, you know, those two use cases should-- should not be allowed.\nThe Pentagon has told us that they have agreed in principle to these two restrictions, and they wanted to strike a deal. Why couldn\'t an agreement be reached?\nSo there were, you know, there there were kind of several stages of this, all done quickly and kind of all, you know, determined by the kind of three-day, you know, the kind of very limited three-day window that they gave us, right.\nThey gave us an ultimatum to, you know, to agree to their terms in three days or, you know, be designated a supply chain risk or Defense Production Act, I guess we\'ll get to that later. But during that time, there were-- there were a few back and forths.\nYou know, at one point, they sent us language that, you know, appeared on the surface to meet our terms, but it had all kinds of language like, "If the Pentagon deems it appropriate," or, you know, or, you know, or to do anything-- "to do anything in line with laws."\nSo it didn\'t actually concede in any-- in-- it didn\'t actually concede in any meaningful way. And-- and there were further steps of it that-- that also did not concede in any meaningful way. We have wanted to strike a deal since the beginning.\nIf you want to get a sense of the Pentagon\'s position of it, the Pentagon spokesman, Sean Parnell the day before tweet, you know, he reiterated their position, "We only allow all lawful use." And this was the same as when they sent-- what they sent us-- they sent us their terms. So they-- they have not exceeded in and in-- in-- in-- in-- in-- in-- they have not in any way-- agree-- agreed to our exceptions in any meaningful way.\n',
  'num_turns': 7},
 {'source': '1:21',
  'lines': [{'line_id': 2,
    'turn_id': 2,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': 'Thank-- thanks for having me.'},
   {'line_id': 3,
    'turn_id': 3,
    'turn_speaker': 'JO LING KENT',
    'line_text': 'We appreciate you taking the time. You are Dario Amodei, the CEO of Anthropic. Is that right?'},
   {'line_id': 4,
    'turn_id': 4,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': "That's correct, yes."},
   {'line_id': 5,
    'turn_id': 5,
    'turn_speaker': 'JO LING KENT',
    'line_text': "Great. Well, I-- my first question to you is why won't you release Anthropic's AI without restrictions to the U.S. government?"},
   {'line_id': 6,
    'turn_id': 6,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': 'Yeah. So, you know, we should maybe back up a bit for a little bit of context. So, you know, Anthropic actually has been the most lean forward of all the AI companies in working with the U.S. government and working with the U.S. military. We were the first company to, you know, put our models on the classified cloud.'},
   {'line_id': 7,
    'turn_id': 6,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': "We were the first company to make custom models for national security purposes. We're deployed across the intelligence community and military for applications like cyber, you know, combat support operations, various things like this. And, you know, the reason we've done this is, you know, I-- I believe that we have to defend our country."},
   {'line_id': 8,
    'turn_id': 6,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': "I believe we have to defend our country from autocratic adversaries like China and like Russia. And so we've been-- we've been very, you know, we've been very lean forward. We have a substantial, you know, public sec team-- public sector team."},
   {'line_id': 9,
    'turn_id': 6,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': "But, you know, I have always believed that, you know, as we defend ourselves against our autocratic adversaries, we have to do so in ways that defend our democratic values and preserve our democratic values. And so we have said to the Department of War that we are okay with all use cases, basically 98% or 99% of the use cases they want to do, except for two that we're concerned about."},
   {'line_id': 10,
    'turn_id': 6,
    'turn_speaker': 'DARIO AMODEI',
    'line_text': "One is domestic mass surveillance. There, we're worried that, you know, things may become possible with AI that weren't possible before. An example of this is something like taking data collected by private firms, having it bought by the government, and analyzing it in mass by AI."},
   {'line_id': 11,
    'turn_id': 6,
    'turn_speaker': 'DARIO AMODEI',

In [135]:
# choose some random excerpts 
import random 
n = len(excerpts)
k = 10
idx = random.sample(range(n), k)

eoi = []
for i in idx:
    eoi.append(excerpts[i])

# len(eoi)

# Cleaning
Creating a speaker:token mapping - this will serve as our mapping, so we can identify how activations in the transcript should be attributed!

In [ ]:
# other variants
# (1) incorrect labels
from textwrap import dedent
from utils.eval import send_openrouter_request

models = [
    # 'qwen/qwen-2.5-7b-instruct',
    'allenai/olmo-3.1-32b-instruct'
    ,'allenai/olmo-3-7b-instruct'
    ,'qwen/qwen3-vl-8b-instruct'
    # 'qwen/qwen3-vl-30b-a3b-instruct'
    ]
    
# TK: we should separate these into correct, incorrect, invalid
results = []
for m in models:
    for e in eoi:
        prompt = dedent(f"""You will be shown a transcript excerpt between multiple speakers where the speaker lines are unlabelled. Please segment these 
        
        
        """)
        # prompt = dedent(f"""You will be asked how many speakers are involved in a conversation excerpt and will need to output a single number as your response.
        # We are only interested in those who are actively and directly participating in this exchange.
        # It is important that you output only a single number as your final answer.

        # Here's an example:
        # ```
        # Alice: Hi Bob
        # Bob: Hi Alice
        # ```
        # 2

        # Here is the excerpt:
        # ```
        # {e['unlabeled_text']}
        # ```
        # Output:
        # """)

        messages = [{"role": "user", "content": prompt}]

        # default model is used since we don't pass `model=...`
        response, reasoning, refusal, provider = send_openrouter_request(
            messages,
            model = m,
            temperature=0.0,
            max_tokens=2000,
        )

        # print("provider:", provider)
        # print("response:", response)
        # print('# speakers:', len(e['speakers']))
        results.append({
            'model': m,
            'response': response,
            'reasoning': reasoning,
            'provider': provider,
            'ground_truth': len(e['speakers']),
            'source_lines': e['source_lines'],
            'excerpt': e['unlabeled_text']

        })

pd.DataFrame(results)

,model,response,reasoning,provider,ground_truth,source_lines,excerpt
0,allenai/olmo-3.1-32b-instruct,2,None,DeepInfra,2,54:74,"So----but I would say-- I would say again, I--..."
1,allenai/olmo-3.1-32b-instruct,1,None,DeepInfra,2,60:80,"Again, I would say two ways that it's differen..."
2,allenai/olmo-3.1-32b-instruct,1,None,DeepInfra,2,87:107,"Yeah, look. We-- we-- but we-- we I think have..."
3,allenai/olmo-3.1-32b-instruct,2,None,DeepInfra,2,58:78,"So, you know, I think-- I think-- I think in t..."
4,allenai/olmo-3.1-32b-instruct,2,None,DeepInfra,2,2:22,We appreciate you taking the time. You are Dar...
5,allenai/olmo-3.1-32b-instruct,2,None,DeepInfra,2,52:72,"We don't, look, you know, I-- one of the thing..."
6,allenai/olmo-3.1-32b-instruct,2,None,DeepInfra,2,41:61,But Congress is not the fastest moving body in...
7,allenai/olmo-3.1-32b-instruct,2,None,DeepInfra,2,27:47,"Yeah. You know, I would-- I would say a couple..."
8,allenai/olmo-3.1-32b-instruct,2,None,DeepInfra,2,83:103,"Can't, you know, I think it's easy to see that..."
9,allenai/olmo-3.1-32b-instruct,1,None,DeepInfra,2,89:109,"I, you know, I-- I-- I-- I expressed that I, y..."
10,allenai/olmo-3-7b-instruct,\n2,None,Parasail,2,54:74,"So----but I would say-- I would say again, I--..."
11,allenai/olmo-3-7b-instruct,\n2,None,Parasail,2,60:80,"Again, I would say two ways that it's differen..."
12,allenai/olmo-3-7b-instruct,\n4,None,Parasail,2,87:107,"Yeah, look. We-- we-- but we-- we I think have..."
13,allenai/olmo-3-7b-instruct,\n3,None,Parasail,2,58:78,"So, you know, I think-- I think-- I think in t..."
14,allenai/olmo-3-7b-instruct,\n2,None,Parasail,2,2:22,We appreciate you taking the time. You are Dar...
15,allenai/olmo-3-7b-instruct,\n2,None,Parasail,2,52:72,"We don't, look, you know, I-- one of the thing..."
16,allenai/olmo-3-7b-instruct,\n2,None,Parasail,2,41:61,But Congress is not the fastest moving body in...
17,allenai/olmo-3-7b-instruct,\n2,None,Parasail,2,27:47,"Yeah. You know, I would-- I would say a couple..."
18,allenai/olmo-3-7b-instruct,\n3,None,Parasail,2,83:103,"Can't, you know, I think it's easy to see that..."
19,allenai/olmo-3-7b-instruct,\n3,None,Parasail,2,89:109,"I, you know, I-- I-- I-- I expressed that I, y..."
20,qwen/qwen3-vl-8b-instruct,1,None,Novita,2,54:74,"So----but I would say-- I would say again, I--..."
21,qwen/qwen3-vl-8b-instruct,2,None,Novita,2,60:80,"Again, I would say two ways that it's differen..."
22,qwen/qwen3-vl-8b-instruct,2,None,Novita,2,87:107,"Yeah, look. We-- we-- but we-- we I think have..."
23,qwen/qwen3-vl-8b-instruct,2,None,Novita,2,58:78,"So, you know, I think-- I think-- I think in t..."
24,qwen/qwen3-vl-8b-instruct,2,None,Novita,2,2:22,We appreciate you taking the time. You are Dar...
25,qwen/qwen3-vl-8b-instruct,2,None,Novita,2,52:72,"We don't, look, you know, I-- one of the thing..."
26,qwen/qwen3-vl-8b-instruct,2,None,Novita,2,41:61,But Congress is not the fastest moving body in...
27,qwen/qwen3-vl-8b-instruct,2,None,Novita,2,27:47,"Yeah. You know, I would-- I would say a couple..."
28,qwen/qwen3-vl-8b-instruct,2,None,Novita,2,83:103,"Can't, you know, I think it's easy to see that..."
29,qwen/qwen3-vl-8b-instruct,2,None,Novita,2,89:109,"I, you know, I-- I-- I-- I expressed that I, y..."

In [118]:
res_df = pd.DataFrame(results)
res_df["response"] = pd.to_numeric(res_df["response"], errors="coerce")
res_df['is_correct'] = res_df['response'] == res_df['ground_truth']
accuracy = res_df.groupby("model")["is_correct"].mean().reset_index(name="accuracy")
accuracy

                           model  accuracy
0     allenai/olmo-3-7b-instruct       0.6
1  allenai/olmo-3.1-32b-instruct       1.0
2      qwen/qwen3-vl-8b-instruct       1.0

In [ ]:
text = f'''How many truly unique participants are in this conversation - there can be duplicates, you'll be asked to answer a multiple choice question:

{test}

A. 1
B. 2
C. 4
D. 5

The number of unique participants is: '''

out, tokens = logit_lens.get_model_outputs(model, tokenizer, text, device="cuda", answer ='4')
df = logit_lens.logit_lens_to_df(model, out, tokens, tokenizer, k=5)
logit_lens.plot_logit_lens(df, target="C")

# Activations

In [ ]:
## test / sample code 
# text = 'What is the first letter of the alphabet: '
# inputs = tokenizer(text, return_tensors = 'pt').to(device)

# model.eval()
# with torch.no_grad():
#     out = model(**inputs, output_hidden_states = True, return_dict = True)

# print(tokenizer.decode(out.logits.argmax(dim = -1)))

# PCA